"use client";
import { useEffect, useState, type FormEvent } from "react";
import type { Viewer, TesseraRole } from "@/lib/auth/authorization";
import { canAdminister } from "@/lib/auth/authorization";

type Organization={id:string;name:string;active:boolean};
type Project={id:string;organizationId:string;name:string;active:boolean};
type Person={id:string;displayName:string;email:string;accountType:"consultant"|"customer";active:boolean};
type Membership={id:string;userId:string;organizationId?:string;projectId?:string;role:TesseraRole};
type Invitation={id:string;email:string;accountType:string;role:string;organizationId:string;projectId:string|null;status:string;expiresAt:string};
type AdminData={organizations:Organization[];projects:Project[];users:Person[];organizationMemberships:Membership[];projectMemberships:Membership[];settings:{name:string;defaultMark:string};events:{id:string;eventType:string;actorName:string|null;createdAt:string}[]};
const labels:Record<string,string>={customer_user:"Customer user",customer_manager:"Customer manager",consultant:"Consultant",engagement_lead:"Engagement lead",operations_manager:"Operations manager",administrator:"Administrator",auditor:"Auditor"};
async function request<T>(url:string,method="GET",input?:unknown):Promise<T>{
  const response=await fetch(url,{method,credentials:"same-origin",cache:"no-store",headers:input?{"Content-Type":"application/json"}:undefined,body:input?JSON.stringify(input):undefined});
  if(response.status===401){window.location.assign("/login");throw new Error("Please sign in again");}
  const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to save changes");return result;
}
type Save=(input:Record<string,unknown>,method?:string,url?:string)=>Promise<boolean>;
export function AdministrationPanel({view,viewer,onChanged}:{view:"Clients"|"Team"|"Settings";viewer:Viewer;onChanged:()=>Promise<void>}){
  const [data,setData]=useState<AdminData|null>(null),[invites,setInvites]=useState<Invitation[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
  const authorized=canAdminister(viewer);
  useEffect(()=>{let cancelled=false;async function load(){
    if(!authorized){setLoading(false);return;}setLoading(true);setError("");
    try{const [data,invitations]=await Promise.all([request<AdminData>("/api/admin"),request<{invitations:Invitation[]}>("/api/invitations")]);if(!cancelled){setData(data);setInvites(invitations.invitations);}}
    catch(error){if(!cancelled)setError(error instanceof Error?error.message:"Unable to load this page");}finally{if(!cancelled)setLoading(false);}
  }void load();return ()=>{cancelled=true;};},[authorized,version]);
  const save:Save=async(input,method="PATCH",url="/api/admin")=>{
    if(busy)return false;setBusy(true);setError("");setNotice("");
    try{await request(url,method,input);setNotice(url==="/api/invitations"&&method==="POST"?"Invitation sent.":"Changes saved.");setVersion(value=>value+1);await onChanged();return true;}
    catch(error){setError(error instanceof Error?error.message:"Unable to save changes");return false;}finally{setBusy(false);}
  };
  if(!authorized)return <div className="workspace-panel"><article className="panel-card"><h2>{view}</h2><p>Client and team administration requires an Administrator or Operations manager account.</p></article></div>;
  return <div className="workspace-panel admin-panel">{error&&<div className="login-error" role="alert">{error}<button onClick={()=>setVersion(value=>value+1)}>Retry loading</button></div>}{notice&&<div className="confirmation" role="status">{notice}</div>}{loading?<p role="status">Loading {view.toLowerCase()}…</p>:data&&<>{view==="Clients"?<Clients data={data} save={save} busy={busy}/>:view==="Team"?<Team data={data} invites={invites} viewer={viewer} save={save} busy={busy}/>:<Settings data={data} save={save} busy={busy}/>}</>}</div>;
}
function Clients({data,save,busy}:{data:AdminData;save:Save;busy:boolean}){
  const [search,setSearch]=useState(""),[archived,setArchived]=useState(false);
  async function create(event:FormEvent<HTMLFormElement>,action:string){event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form));if(await save({action,...values},"POST"))form.reset();}
  const clients=data.organizations.filter(org=>(archived||org.active)&&(org.name+data.projects.filter(project=>project.organizationId===org.id).map(project=>project.name).join(" ")).toLowerCase().includes(search.toLowerCase()));
  return <><div className="admin-intro"><p>Manage client organizations and the projects your team supports.</p><label>Search clients and projects<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Find a client or project"/></label><label className="admin-check"><input type="checkbox" checked={archived} onChange={event=>setArchived(event.target.checked)}/>Include archived clients</label></div><div className="admin-form-grid"><form className="panel-card" onSubmit={event=>create(event,"organization")}><h2>Add a client</h2><label>Client name<input name="name" required minLength={2} maxLength={120} placeholder="Organization name"/></label><button className="primary" disabled={busy}>Add client</button></form><form className="panel-card" onSubmit={event=>create(event,"project")}><h2>Add a project</h2><label>Client<select name="organizationId" required defaultValue=""><option value="" disabled>Choose a client</option>{data.organizations.filter(org=>org.active).map(org=><option value={org.id} key={org.id}>{org.name}</option>)}</select></label><label>Project name<input name="name" required minLength={2} maxLength={120} placeholder="Project name"/></label><button className="primary" disabled={busy||!data.organizations.some(org=>org.active)}>Add project</button></form></div><section className="client-grid">{clients.map(org=><article className="client-card" key={org.id}><EditableName key={org.name} name={org.name} label="Client name" disabled={busy} onSave={name=>save({action:"organization",id:org.id,name})}/><p>{org.active?"Active client":"Archived client"}</p><button className="admin-secondary" disabled={busy} onClick={()=>save({action:"organization",id:org.id,active:!org.active})}>{org.active?"Archive client":"Restore client"}</button><h3>Projects</h3>{data.projects.filter(project=>project.organizationId===org.id).map(project=><div className="admin-project" key={project.id}><EditableName key={project.name} name={project.name} label="Project name" disabled={busy} onSave={name=>save({action:"project",id:project.id,name})}/><button disabled={busy} onClick={()=>save({action:"project",id:project.id,active:!project.active})}>{project.active?"Archive project":"Restore project"}</button></div>)}{!data.projects.some(project=>project.organizationId===org.id)&&<p>No projects yet. Add one above to start opening Tesserae.</p>}</article>)}</section>{!clients.length&&<article className="panel-card"><h2>No clients found</h2><p>Add a client above or change your search.</p></article>}</>;
}
function EditableName({name,label,disabled,onSave}:{name:string;label:string;disabled:boolean;onSave:(value:string)=>Promise<boolean>}){
  const [editing,setEditing]=useState(false),[value,setValue]=useState(name);
  if(!editing)return <div className="admin-name"><h2>{name}</h2><button disabled={disabled} onClick={()=>setEditing(true)}>Rename</button></div>;
  return <form onSubmit={async event=>{event.preventDefault();if(await onSave(value))setEditing(false);}}><label>{label}<input required minLength={2} maxLength={120} value={value} onChange={event=>setValue(event.target.value)}/></label><div className="admin-actions"><button disabled={disabled} className="primary">Save name</button><button type="button" onClick={()=>setEditing(false)}>Cancel</button></div></form>;
}
function ScopeFields({data,accountType,allowAdmin=true}:{data:AdminData;accountType:string;allowAdmin?:boolean}){
  const [org,setOrg]=useState(""),[role,setRole]=useState(accountType==="customer"?"customer_user":"consultant");
  return <><label>Organization<select name="organizationId" required value={org} onChange={event=>setOrg(event.target.value)}><option value="">Choose an organization</option>{data.organizations.filter(org=>org.active).map(org=><option value={org.id} key={org.id}>{org.name}</option>)}</select></label><label>Role<select name="role" value={role} onChange={event=>setRole(event.target.value)}>{Object.entries(labels).filter(([role])=>accountType==="customer"?role.startsWith("customer_"):!role.startsWith("customer_")&&(allowAdmin||role!=="administrator")).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{!["administrator","operations_manager"].includes(role)&&<label>Project access<select name="projectId" key={org} defaultValue=""><option value="">All projects in this organization</option>{data.projects.filter(project=>project.active&&project.organizationId===org).map(project=><option value={project.id} key={project.id}>{project.name}</option>)}</select></label>}{role==="administrator"&&<p className="admin-hint">Administrators can manage all clients, projects, accounts, and workspace settings.</p>}</>;
}
function Team({data,invites,viewer,save,busy}:{data:AdminData;invites:Invitation[];viewer:Viewer;save:Save;busy:boolean}){
  const [type,setType]=useState("consultant"),[search,setSearch]=useState("");
  const allowAdmin=viewer.memberships.some(member=>member.role==="administrator");
  async function invite(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(await save({...Object.fromEntries(new FormData(form)),accountType:type},"POST","/api/invitations"))form.reset();}
  return <><div className="admin-form-grid"><form className="panel-card" onSubmit={invite}><h2>Invite an account</h2><p>Send an invitation and assign the person’s access before they sign in.</p><label>Email address<input name="email" type="email" required placeholder="name@company.com"/></label><label>Account type<select value={type} onChange={event=>setType(event.target.value)}><option value="consultant">Consultant</option><option value="customer">Customer</option></select></label><ScopeFields key={type} data={data} accountType={type} allowAdmin={allowAdmin}/><button className="primary" disabled={busy}>Send invitation</button></form><article className="panel-card"><h2>Pending invitations</h2>{invites.filter(invite=>invite.status==="pending").map(invite=><div className="admin-invite" key={invite.id}><b>{invite.email}</b><small>{labels[invite.role]} · {data.organizations.find(org=>org.id===invite.organizationId)?.name}</small><small>{new Date(invite.expiresAt)>new Date()?"Expires":"Expired"} {new Date(invite.expiresAt).toLocaleDateString()}</small><button disabled={busy} onClick={()=>save({id:invite.id},"PATCH","/api/invitations")}>Revoke invitation</button></div>)}{!invites.some(invite=>invite.status==="pending")&&<p>No pending invitations.</p>}</article></div><label>Search accounts<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Name or email address"/></label><section className="admin-people">{data.users.filter(person=>`${person.displayName} ${person.email}`.toLowerCase().includes(search.toLowerCase())).map(person=><PersonCard key={person.id} person={person} data={data} viewer={viewer} save={save} busy={busy} allowAdmin={allowAdmin}/>)}</section></>;
}
function PersonCard({person,data,viewer,save,busy,allowAdmin}:{person:Person;data:AdminData;viewer:Viewer;save:Save;busy:boolean;allowAdmin:boolean}){
  const [editing,setEditing]=useState(false),own=viewer.userId===person.id;
  const memberships=[...data.organizationMemberships,...data.projectMemberships].filter(member=>member.userId===person.id);
  const protectedAdmin=!allowAdmin&&memberships.some(member=>member.role==="administrator");
  return <article className="panel-card"><div className="admin-name"><h2>{person.displayName}</h2><span className={`status ${person.active?"Open":"Waiting"}`}>{person.active?"Active":"Disabled"}</span></div><p>{person.email} · {person.accountType}</p>{memberships.map(member=><div className="admin-membership" key={member.id}><span><b>{labels[member.role]}</b><small>{member.projectId?data.projects.find(project=>project.id===member.projectId)?.name:data.organizations.find(org=>org.id===member.organizationId)?.name}</small></span>{!own&&!protectedAdmin&&<button disabled={busy} onClick={()=>save({action:"revokeMembership",userId:person.id,organizationId:member.organizationId,projectId:member.projectId})}>Remove access</button>}</div>)}{!memberships.length&&<p>No organization or project access assigned.</p>}{own?<p className="admin-hint">This is your account. Another administrator can change your access.</p>:!protectedAdmin&&<div className="admin-actions"><button disabled={busy} onClick={()=>setEditing(!editing)}>{editing?"Cancel":"Manage access"}</button><button disabled={busy} onClick={()=>save({action:"account",userId:person.id,active:!person.active})}>{person.active?"Disable account":"Enable account"}</button></div>}{editing&&<form onSubmit={async event=>{event.preventDefault();if(await save({action:"membership",userId:person.id,...Object.fromEntries(new FormData(event.currentTarget))}))setEditing(false);}}><h3>Add or update access</h3><ScopeFields data={data} accountType={person.accountType} allowAdmin={allowAdmin}/><button disabled={busy} className="primary">Save access</button></form>}</article>;
}
function Settings({data,save,busy}:{data:AdminData;save:Save;busy:boolean}){
  return <div className="admin-form-grid"><form className="panel-card" onSubmit={event=>{event.preventDefault();void save({action:"settings",...Object.fromEntries(new FormData(event.currentTarget))});}}><h2>Workspace defaults</h2><label>Workspace name<input required name="name" minLength={2} maxLength={120} defaultValue={data.settings.name}/></label><label>Default Mark<select name="defaultMark" defaultValue={data.settings.defaultMark}>{["low","normal","high","urgent"].map(mark=><option value={mark} key={mark}>{mark[0].toUpperCase()+mark.slice(1)}</option>)}</select></label><button disabled={busy} className="primary">Save settings</button><h3>Access policy</h3><p>Accounts require an invitation. Access is controlled by organization and project memberships.</p><p>Administrator access covers the entire workspace. You cannot disable yourself or remove your own access.</p></form><article className="panel-card"><h2>Administration history</h2><p>Latest client, project, account, and settings changes.</p>{data.events.map(event=><div className="admin-invite" key={event.id}><b>{event.eventType.replaceAll("."," ").replaceAll("_"," ")}</b><small>{event.actorName||"System"} · {new Date(event.createdAt).toLocaleString()}</small></div>)}{!data.events.length&&<p>No administration changes recorded yet.</p>}</article></div>;
}

