"use client";

import { Building2, CheckCircle2, Clock3, Inbox, Plus, ShieldCheck, UserPlus, Users } from "lucide-react";
import { FormEvent, useState } from "react";

export type WorkspaceTicket={id:number;client:string;project:string;owner:string;status:string;priority:string;due:string};
type View="Overview"|"Clients"|"Team"|"Settings";

const clients=[
 {name:"Acme Corp",initials:"AC",projects:["ERP modernization","Finance transformation"],lead:"Sofia Garcia",health:"On track"},
 {name:"Northstar Foods",initials:"NF",projects:["Controls optimization"],lead:"Daniel Ortiz",health:"Needs attention"},
 {name:"Greenline Energy",initials:"GE",projects:["Analytics enablement"],lead:"Priya Shah",health:"On track"},
 {name:"Vantage Health",initials:"VH",projects:["Platform assessment"],lead:"Sofia Garcia",health:"On track"},
];
const people=[
 {name:"Sofia Garcia",email:"sofia@consulting.example",role:"Engagement lead",scope:"Acme Corp · Vantage Health",status:"Active"},
 {name:"Priya Shah",email:"priya@consulting.example",role:"Consultant",scope:"Greenline Energy",status:"Active"},
 {name:"Daniel Ortiz",email:"daniel@consulting.example",role:"Consultant",scope:"Northstar Foods",status:"Active"},
 {name:"Maya Chen",email:"maya@acme.example",role:"Customer manager",scope:"Acme Corp",status:"Invited"},
];

export function WorkspacePanel({view,tickets,notify}:{view:View;tickets:WorkspaceTicket[];notify:(message:string)=>void}){
 if(view==="Overview") return <Overview tickets={tickets}/>;
 if(view==="Clients") return <Clients tickets={tickets} notify={notify}/>;
 if(view==="Team") return <Team notify={notify}/>;
 return <Settings notify={notify}/>;
}

function Overview({tickets}:{tickets:WorkspaceTicket[]}){
 const open=tickets.filter(t=>t.status!=="Redeemed").length, urgent=tickets.filter(t=>t.priority==="Urgent").length, due=tickets.filter(t=>t.due.startsWith("Today")).length;
 return <div className="workspace-panel overview-panel"><section className="metric-grid"><Metric icon={<Inbox/>} label="Active Tesserae" value={open} note="Across 4 client organizations"/><Metric icon={<Clock3/>} label="Due today" value={due} note="Two deadlines before 6 PM"/><Metric icon={<ShieldCheck/>} label="Urgent Mark" value={urgent} note="Immediate attention required"/><Metric icon={<Users/>} label="Unassigned" value={tickets.filter(t=>t.owner==="Unassigned").length} note="Ready for triage"/></section><section className="overview-grid"><article className="panel-card"><header><div><h2>Client workload</h2><p>Active work by organization</p></div></header>{clients.map(client=>{const count=tickets.filter(t=>t.client===client.name).length;return <div className="workload" key={client.name}><strong>{client.initials}</strong><span><b>{client.name}</b><small>{client.projects.length} active {client.projects.length===1?"project":"projects"}</small></span><div><i style={{width:`${Math.max(18,count*28)}%`}}/><small>{count} Tesserae</small></div></div>})}</article><article className="panel-card"><header><div><h2>Today’s priorities</h2><p>Items that need a decision</p></div></header>{tickets.filter(t=>t.due.startsWith("Today")||t.priority==="Urgent").map(t=><div className="priority-row" key={t.id}><span className={`mark-dot ${t.priority.toLowerCase()}`}/><div><b>#{t.id} · {t.client}</b><small>{t.project}</small></div><em>{t.due}</em></div>)}</article></section></div>
}
function Metric({icon,label,value,note}:{icon:React.ReactNode;label:string;value:number;note:string}){return <article className="metric"><span>{icon}</span><div><small>{label}</small><b>{value}</b><p>{note}</p></div></article>}

function Clients({tickets,notify}:{tickets:WorkspaceTicket[];notify:(m:string)=>void}){return <div className="workspace-panel"><div className="panel-actions"><label><input placeholder="Search clients and projects"/></label><button className="primary" onClick={()=>notify("The new-client form is ready for database connection.")}><Plus/>New client</button></div><section className="client-grid">{clients.map(client=><article className="client-card" key={client.name}><header><strong>{client.initials}</strong><div><h2>{client.name}</h2><p>{client.projects.length} active {client.projects.length===1?"project":"projects"}</p></div><span className={client.health==="On track"?"healthy":"attention"}>{client.health}</span></header><dl><div><dt>Open Tesserae</dt><dd>{tickets.filter(t=>t.client===client.name).length}</dd></div><div><dt>Engagement lead</dt><dd>{client.lead}</dd></div></dl><h3>Projects</h3>{client.projects.map(project=><button className="project-row" key={project}><span><Building2/><b>{project}</b></span><small>View engagement →</small></button>)}</article>)}</section></div>}

function Team({notify}:{notify:(m:string)=>void}){const [invite,setInvite]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setInvite(false);notify("Invitation prepared. It will send after Netlify Identity is connected.")}return <div className="workspace-panel"><div className="panel-actions"><div><h2>Accounts and access</h2><p>Consultants and customers only see their assigned organizations and projects.</p></div><button className="primary" onClick={()=>setInvite(true)}><UserPlus/>Invite account</button></div><section className="people-table"><header><span>Person</span><span>Role</span><span>Access scope</span><span>Status</span></header>{people.map(person=><div key={person.email}><span className="person-cell"><strong>{person.name.split(" ").map(x=>x[0]).join("")}</strong><i><b>{person.name}</b><small>{person.email}</small></i></span><span>{person.role}</span><span>{person.scope}</span><span><em className={person.status.toLowerCase()}>{person.status}</em></span></div>)}</section>{invite&&<div className="inline-form"><form onSubmit={submit}><header><div><h2>Invite an account</h2><p>Assign the narrowest access the person needs.</p></div><button type="button" onClick={()=>setInvite(false)}>×</button></header><label>Email<input type="email" required placeholder="name@company.com"/></label><section><label>Account type<select><option>Customer</option><option>Consultant</option></select></label><label>Role<select><option>Customer user</option><option>Customer manager</option><option>Consultant</option><option>Engagement lead</option></select></label></section><label>Organization<select><option>Acme Corp</option><option>Northstar Foods</option><option>Greenline Energy</option><option>Vantage Health</option></select></label><footer><button type="button" onClick={()=>setInvite(false)}>Cancel</button><button className="primary">Prepare invitation</button></footer></form></div>}</div>}

function Settings({notify}:{notify:(m:string)=>void}){return <div className="workspace-panel settings-grid"><section className="panel-card settings-nav"><button className="active">General</button><button>Marks and statuses</button><button>Security</button><button>Notifications</button><button>Audit history</button></section><section className="panel-card settings-form"><header><div><h2>Workspace settings</h2><p>Defaults for the consulting service desk.</p></div></header><label>Workspace name<input defaultValue="Tessera"/></label><label>Default Mark<select defaultValue="Normal"><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label><label>Default assignee<select defaultValue="Unassigned"><option>Unassigned</option><option>Engagement lead</option><option>Operations manager</option></select></label><div className="setting-row"><span><b>Invite-only accounts</b><small>Only administrators can create customer or consultant accounts.</small></span><input type="checkbox" defaultChecked/></div><div className="setting-row"><span><b>Require consultant MFA</b><small>Enforced when Netlify Identity is connected.</small></span><input type="checkbox" defaultChecked/></div><div className="setting-row"><span><b>Customer-safe not-found responses</b><small>Do not reveal whether inaccessible records exist.</small></span><input type="checkbox" defaultChecked disabled/></div><footer><button className="primary" onClick={()=>notify("Workspace settings saved locally.")}><CheckCircle2/>Save changes</button></footer></section></div>}
